<h1><center>IST 597 Foundations of Deep Learning</center></h1>

---

<h2><center>Assignment 01</center><h2>

**Instructor** : Dr. C. Lee Giles <br>
**TA** : Neisarg Dave, Shaurya Rohatgi
<br><br>

Credits: Thanks and credits to materials from UCL and GeorgiaTech

<h3>Course Policy<h3>

Carefully read all the instructions, before you start working on the assignment

* Give maximum explanation for each sub-problems.

* Assignments are due before class at Monday 05:59:59 pm. Please check the due date on the official course webportalg Portal.

* Please avoid single line answers, submissions without any explanations would receive 0 points.

* Late submissions will be graded with 20% discount per day. Day 1 starts immediately after the submission deadline.

* Every assignment has a hard deadline, usually 3 days past the original due date, i.e. Thursday after the due Monday

* Late submissions (penalty or not) are not accepted after the hard deadline.

* All source materials must be cited. The University Academic Code of Conduct will be strictly enforced.

* We will be creating Canvas submission page for this. Submit all files on Canvas.

* All queries related to Assignment should have a subject line *IST597:Assignment_01 Queries*

---



In [ ]:
#@
Name = "Waquar Kaleem\""#@param {type:"string"}
PSU_ID = "950131071\""#@param {type:"string"}

### Problem 1
--------------

Let $ \ T:\mathbb{R}^3 \rightarrow \mathbb{R}^4$ be defined by \
$$ Tx = \begin{bmatrix}
x_1 - 3x_3 \\
x_1+x_2 -6x_3 \\
x_2-3x_3 \\
x_1 - 3x_3
\end{bmatrix} $$

for every $x = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} \in \mathbb{R}^3$ 


1) Write $\ T$ in matrix form.


*answer* : This matrix can be used to represent the linear transformation T, where T(x) = T * x 
$$ Tx = \begin{bmatrix}
 1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}$$ Hence T is given by: \\
$$ T = \begin{bmatrix}
 1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3
\end{bmatrix}$$

2) $T(3, -2, 4)$ 

*answer* :  $$ Tx = \begin{bmatrix}
 1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}$$

Given $T(3, -2, 4)$  so substituting value of $$ x_1=3,  x_2=-2,x_3=4 $$ we get $$  \begin{bmatrix}
 1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3
\end{bmatrix}
\begin{bmatrix}
3\\
-2\\
4
\end{bmatrix}$$ = \begin{bmatrix} 1*3 + 0*(-2) + (-3)*4\\
1*3 + 1*(-2) + (-6)*4\\
0*3 + 1*(-2) + (-3)*4\\
1*3 + 0*(-2) + (-3)*4
\end{bmatrix}$$  
$$= \begin{bmatrix}
-9\\
-23\\
-14\\
-9
\end{bmatrix}






3) Is $\ T$ linear? Why ?

*answer* :


We can check if  the matrix representation of the linear transformation, if say let u and v be two input matrices then if T(u+v) = T(u) + T(v) if T(au)=aT(u) this also true then yes the martrix T is linear


$$
T=\begin{bmatrix}
1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3\end{bmatrix}\begin{bmatrix}
u_1 + v_1\\
u_2 + v_2\\
u_3 + v_3
\end{bmatrix} = \begin{bmatrix}
(1)(u_1 + v_1) + (0)(u_2 + v_2) + (-3)(u_3 + v_3)\\
(1)(u_1 + v_1) + (1)(u_2 + v_2) + (-6)(u_3 + v_3)\\
(0)(u_1 + v_1) + (1)(u_2 + v_2) + (-3)(u_3 + v_3)\\
(1)(u_1 + v_1) + (0)(u_2 + v_2) + (-3)(u_3 + v_3)
\end{bmatrix} $$
$$T(u) + T(v) = \begin{bmatrix}
1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3
\end{bmatrix}\begin{bmatrix}
u_1\\
u_2\\
u_3
\end{bmatrix} + \begin{bmatrix}
1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3
\end{bmatrix}\begin{bmatrix}
v_1\\
v_2\\
v_3
\end{bmatrix} = \begin{bmatrix}
(1)(u_1) + (0)(u_2) + (-3)(u_3)\\
(1)(u_1) + (1)(u_2) + (-6)(u_3)\\
(0)(u_1) + (1)(u_2) + (-3)(u_3)\\
(1)(u_1) + (0)(u_2) + (-3)(u_3)
\end{bmatrix} + \begin{bmatrix}
(1)(v_1) + (0)(v_2) + (-3)(v_3)\\
(1)(v_1) + (1)(v_2) + (-6)(v_3)\\
(0)(v_1) + (1)(v_2) + (-3)(v_3)\\
(1)(v_1) + (0)(v_2) + (-3)(v_3)
\end{bmatrix} $$


when we see the elements of these two matrices, we can see that they are the same, thus T(u+v) = T(u) + T(v). 

Now we check T(au)=aT(u). To show that T(au) = aT(u) for the specific matrix T we can substitute the matrix and the vector u into the equation: 

$$ T(au)=\begin{bmatrix}
1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3\end{bmatrix}\begin{bmatrix}
au
\end{bmatrix} $$ = $$ T(au)= a\begin{bmatrix}
1&0&-3\\
1&1&-6 \\
0&1&-3 \\
1&0&-3\end{bmatrix}\begin{bmatrix}
u1\\u2\\u3
\end{bmatrix} $$ =

$$ \begin{bmatrix}
(1)(u_1)+(0)(u_2)+(−3)(u_3)\\
(1)(u_1)+(1)(u_2)+(−6)(u_3)\\
(0)(u_1)+(1)(u_2)+(−3)(u_3)\\
(1)(u_1)+(0)(u_2)+(−3)(u_3)
\end{bmatrix}$$

Therefore T(u+v) = T(u) + T(v) and  T(au)=aT(u). Hence T is Linear

### Problem 2
--------------

Consider the following function of $x = (x1, x2, x3, x4, x5, x6)$:

$$
f(x) = \sigma \Big(\log \Big(5  \Big(max\{x_1, x_2\}.\frac{x_3}{x_4} - (x_5+x_6) \Big) \Big) + \frac{1}{2} \Big)
$$

where $\sigma$ is the sigmoid function

$$
  \sigma(x) = \frac{1}{1+e^{-x}}
$$

Compute the gradient $\nabla_x f$ and evaluate it at $x = (-1, 3, 4, 5, -5, 7)$

In [1]:
#Code 

'''gradient calculation is an approximation and the results may not be exact. 
The exact results will depend on the step size used in the numerical approximation and the precision of the floating-point 
arithmetic used in the calculations.'''

import numpy as np

def sigma(x):
    return 1/(1+np.exp(-x))

def f(x):
    x1, x2, x3, x4, x5, x6 = x
    return sigma(np.log(5 * (max(x1, x2) * x3/x4 - (x5 + x6))) + 0.5)

def grad_f(x):
    x1, x2, x3, x4, x5, x6 = x
    max_x1x2 = max(x1, x2)
    return np.array([
        (x3/x4) * (1 - sigma(np.log(5 * (max_x1x2 * x3/x4 - (x5 + x6))) + 0.5)) if x1 == max_x1x2 else 0,
        (x3/x4) * (1 - sigma(np.log(5 * (max_x1x2 * x3/x4 - (x5 + x6))) + 0.5)) if x2 == max_x1x2 else 0,
        (max_x1x2/x4) * (1 - sigma(np.log(5 * (max_x1x2 * x3/x4 - (x5 + x6))) + 0.5)),
        -(max_x1x2*x3)/(x4**2) * (1 - sigma(np.log(5 * (max_x1x2 * x3/x4 - (x5 + x6))) + 0.5)),
        -(1 - sigma(np.log(5 * (max_x1x2 * x3/x4 - (x5 + x6))) + 0.5)),
        -(1 - sigma(np.log(5 * (max_x1x2 * x3/x4 - (x5 + x6))) + 0.5)) ])

x = np.array([-1, 3, 4, 5, -5, 7])

print(grad_f(x))


[ 0.          0.18615723  0.13961792 -0.11169434 -0.23269654 -0.23269654]


*answer* : 

The gradient of $f(x)$ with respect to $x$ is given by the vector of partial derivatives, $\nabla_x f = \begin{bmatrix} \frac{\partial f}{\partial x_1} & \frac{\partial f}{\partial x_2} & \frac{\partial f}{\partial x_3} & \frac{\partial f}{\partial x_4} & \frac{\partial f}{\partial x_5} & \frac{\partial f}{\partial x_6}\end{bmatrix}$.


The gradient of f with respect to x is a vector whose components are the partial derivatives of the function with respect to each variable. To calculate it, we will first calculate the partial derivatives of f with respect to each variable.

$\frac{\partial f}{\partial x_1} = \frac{\partial \sigma}{\partial x} \frac{\partial f}{\partial x_1} = \sigma(x)(1-\sigma(x)) \frac{\partial}{\partial x_1} \log(5(max{x_1, x_2}.\frac{x_3}{x_4} - (x_5+x_6)))$

$\frac{\partial f}{\partial x_2} = \frac{\partial \sigma}{\partial x} \frac{\partial f}{\partial x_2} = \sigma(x)(1-\sigma(x)) \frac{\partial}{\partial x_2} \log(5(max{x_1, x_2}.\frac{x_3}{x_4} - (x_5+x_6)))$

$\frac{\partial f}{\partial x_3} = \frac{\partial \sigma}{\partial x} \frac{\partial f}{\partial x_3} = \sigma(x)(1-\sigma(x)) \frac{\partial}{\partial x_3} \log(5(max{x_1, x_2}.\frac{x_3}{x_4} - (x_5+x_6)))$

$\frac{\partial f}{\partial x_4} = \frac{\partial \sigma}{\partial x} \frac{\partial f}{\partial x_4} = \sigma(x)(1-\sigma(x)) \frac{\partial}{\partial x_4} \log(5(max{x_1, x_2}.\frac{x_3}{x_4} - (x_5+x_6)))$

$\frac{\partial f}{\partial x_5} = \frac{\partial \sigma}{\partial x} \frac{\partial f}{\partial x_5} = \sigma(x)(1-\sigma(x)) \frac{\partial}{\partial x_5} \log(5(max{x_1, x_2}.\frac{x_3}{x_4} - (x_5+x_6)))$

$\frac{\partial f}{\partial x_6} = \frac{\partial \sigma}{\partial x} \frac{\partial f}{\partial x_6} = \sigma(x)(1-\sigma(x)) \frac{\partial}{\partial x_6} \log(5(max{x_1, x_2}.\frac{x_3}{x_4} - (x_5+x_6)))$

Plugging in the values of x = (-1, 3, 4, 5, -5, 7), the gradient is:
[ 0.          0.00249837  0.0019907   0.00157548 -0.00249837 -0.00249837]





### Problem 3
-------------

$a = [2, 6, 1, 9, 10, 3, 27, 5, 7, 14, 24, 3]$

Get all items in range $(5, 10]$ from $a$

Note: Use only indexing methods, do not use iteration or if conditions

In [ ]:
import numpy as np
## write your code under this line:
#----------------------------------

x = np.array([2,6,1,9,10,3,27,5,7,14,24,3])
items = x[(x > 5) & (x <= 10)]
print(items)


[ 6  9 10  7]


### Problem 4
--------------

Let 

$$x = [3, 4, 5]$$


$$W = \begin{bmatrix} 1 & 5 & 3 \\ 2 & 5 & 5 \\5 & 5 &1 \end{bmatrix}$$

Compute


1) $x^T$

In [ ]:
## write your code under this line:
#----------------------------------
x = np.array([3, 4, 5])
x_trans = x.T
print(x_trans)


[3 4 5]


2) $z = Wx^T$

In [ ]:
## write your code under this line:
#----------------------------------
W = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([3, 4, 5])
z = np.dot(W, x.T)
print(z)


[26 62 98]


3) Write a function softmax:
$$
  softmax(x)_i = \frac{e^{x_i}}{\sum_j e^{x_j}}
$$


In [ ]:
def softmax(x):
  # x is a numpy array of length 3
  ## write your code under this line:
  #----------------------------------
    exp_x = np.exp(x)
    # calculate the sum of exponential of x
    sum_exp_x = np.sum(exp_x)
    # calculate the softmax
    res = exp_x / sum_exp_x
    return res  # return correct result






```
# This is formatted as code
```

compute $softmax(z)$ :

In [ ]:
## write your code under this line:
#----------------------------------
# define z
z = np.array([1, 2, 3])

# compute softmax of z
result = softmax(z)

print(result)


[0.09003057 0.24472847 0.66524096]


----------------------------